<?php
ob_start();
session_start();

$siteYear = date('Y');
$dummyEmail = 'amentaxi24.7@gmail.com';
$companyNumber = '12850124';
$domain = 'taxiamen.com';
$siteLink = 'https://' . $domain . '/';
$siteRegister = 'https://' . $domain . '/accounts/register';
$siteLogin = 'https://' . $domain . '/accounts/login';
$site = 'https://' . $domain;
$siteName = 'Amen Taxi';
$siteEmail = "amentaxi24.7@gmail.com";
$siteEmail1 = "support@" . $domain;
$siteEmail2 = "info@" . $domain;
$sitePhone = '+354-8699766';
$sitePhone2 = '+354-8699766';
$siteAddress = 'Spoaholar 4 Reykjavik 111, Iceland.';
$siteAddress2 = '';
$site_whatsapp_num = '+354-8699766';
$siteWhatsApp = 'https://api.whatsapp.com/send?phone=' . $site_whatsapp_num . '&text=Hi ' . $siteName . ', my name is ...! I want to book a taxi';
$siteDomain = $domain;
$siteWhatsAppLink = 'https://api.whatsapp.com/send?phone=' . $site_whatsapp_num . '&text=';
$siteTelegram = 'https://telegram.com/';
$siteTwitter = 'https://twitter.com/';
$siteFacebook = 'https://facebook.com/';
$siteLinkedin = 'https://linkedin.com/';
$siteInstagram = 'https://instagram.com/';
$siteYoutube = 'https://youtube.com/';
